export const TOAST_CALENDAR_ID = {
  SELECTED_PAST_DATE: "SELECTED_PAST_DATE",
  SELECTED_ERROR: "selected_error"
};

export const TOAST_TOKEN = {
  EXPIRED: "EXPIRED",
  INVALID: "INVALID"
};

export const TOAST_FORM_ID = {
  WARNING: "WARNING",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS"
};
